resolved #3795 - matrix collapse-expand icon for vue
surveyjs/survey-library pull request #3796
Opened 2021-12-20 11:56 UTC by novikov82

2021-12-20 13:34 UTC, dmitrykurmanov requested changes
probably we should add the markup test for that element

2021-12-20 15:24 UTC, tsv2013 approved these changes

2021-12-21 07:19 UTC, andrewtelnov approved these changes

2021-12-21 07:52 UTC, novikov82 commented
@dmitrykurmanov @tsv2013 markup tests for this tasks are planned here:
https://github.com/surveyjs/survey-library/issues/3250

2021-12-21 11:00 UTC, merged